#used to validate keys when qr is scanned


print("\n---Program written to validate qr generated by parent code 'ticket_generator.py'---")
print("Type 'quit' to exit program\n\n\n")

while 1:
    chk = input("Enter key: ")
    if(chk.lower() == "quit"):
        break
    
    u = open("used_keys.txt","r")               #checking if the qr is already used
    lines = u.readlines()

    exit = 0
    for line in lines:
        if(int(line) == int(chk)):
            print("qr already used.\n\n")
            exit = 1
            break

    u.close()

    if exit == 1:
        continue

    v = open("valid_keys.txt","r")              #checking if qr is in the list
    lines = v.readlines()

    flag = 0

    for line in lines:
        if(int(line) == int(chk)):
            print("%s - " % chk + "valid qr\n\n")
            flag = 1
            break
    
    if(flag == 1):
        w = open("used_keys.txt","a")
        w.write(chk + "\n")
        w.close()

    else:
        print("FAKE QR.\n\n")